spring:
  application:
    name: clube-livro

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  url: ${APP_URL:}

google:
  books:
    api-key: ${GOOGLE_BOOKS_API_KEY}
    url: https://www.googleapis.com/books/v1/volumes

agendamento:
  convite:
    expiracao:
      cron: "${CONVITE_EXPIRACAO_CRON:0 0 * * * *}"
  votacao:
    encerramento:
      cron: "${VOTACAO_ENCERRAMENTO_CRON:0 0 * * * *}"
