-- Troca a chave primária de t_usuario de UUID para integer sequencial, preservando os
-- dados e as referências existentes.
--
-- Contexto: o schema é gerenciado por ddl-auto=update, que nunca altera o tipo de uma
-- coluna existente. Sem este script, subir o código novo contra o banco atual quebra na
-- primeira query — e um ALTER TABLE direto também não resolveria, porque UUID não tem
-- conversão para integer e há seis tabelas apontando para t_usuario.id.
--
-- Como rodar: aplique ISTO ANTES de subir a versão nova do backend. O script inteiro está
-- numa transação, então qualquer erro desfaz tudo. Ainda assim, tire um backup antes.
--
-- Os ids são atribuídos na ordem de cadastro (created_at), então o usuário mais antigo
-- vira 1. Nada no app depende do valor, mas isso torna o resultado previsível.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Descobre quem aponta para t_usuario.
--
-- Os nomes das constraints e das colunas foram gerados pelo Hibernate; ler o catálogo
-- em vez de escrevê-los à mão evita o script falhar por um nome diferente do esperado.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE referencias_para_usuario ON COMMIT DROP AS
SELECT con.conrelid::regclass::text AS tabela,
       att.attname::text            AS coluna,
       con.conname::text            AS constraint_antiga
  FROM pg_constraint con
  JOIN unnest(con.conkey) AS k(attnum) ON true
  JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = k.attnum
 WHERE con.contype = 'f'
   AND con.confrelid = 't_usuario'::regclass;

-- Se isto vier vazio, algo está errado: pare e investigue antes de continuar.
DO $$
DECLARE total integer;
BEGIN
    SELECT count(*) INTO total FROM referencias_para_usuario;
    RAISE NOTICE 'tabelas referenciando t_usuario: %', total;
    IF total = 0 THEN
        RAISE EXCEPTION 'nenhuma FK para t_usuario encontrada - schema inesperado';
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Numera os usuários existentes.
-- ---------------------------------------------------------------------------
ALTER TABLE t_usuario ADD COLUMN id_int integer;

WITH numerados AS (
    SELECT id, row_number() OVER (ORDER BY created_at NULLS FIRST, id) AS n
      FROM t_usuario
)
UPDATE t_usuario u
   SET id_int = numerados.n
  FROM numerados
 WHERE u.id = numerados.id;

ALTER TABLE t_usuario ALTER COLUMN id_int SET NOT NULL;

-- ---------------------------------------------------------------------------
-- 3. Converte cada coluna que referencia usuário.
--
-- Para cada FK: cria a coluna integer, traduz os UUIDs, derruba a constraint antiga,
-- descarta a coluna UUID e assume o nome dela.
-- ---------------------------------------------------------------------------
DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT * FROM referencias_para_usuario LOOP
        EXECUTE format('ALTER TABLE %s ADD COLUMN %I integer', r.tabela, r.coluna || '_int');

        EXECUTE format(
            'UPDATE %s t SET %I = u.id_int FROM t_usuario u WHERE t.%I = u.id',
            r.tabela, r.coluna || '_int', r.coluna);

        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.tabela, r.constraint_antiga);
        EXECUTE format('ALTER TABLE %s DROP COLUMN %I', r.tabela, r.coluna);
        EXECUTE format('ALTER TABLE %s RENAME COLUMN %I TO %I', r.tabela, r.coluna || '_int', r.coluna);

        RAISE NOTICE 'convertida: %.%', r.tabela, r.coluna;
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 4. Troca a chave primária de t_usuario.
-- ---------------------------------------------------------------------------
DO $$
DECLARE pk_nome text;
BEGIN
    SELECT conname INTO pk_nome
      FROM pg_constraint
     WHERE contype = 'p' AND conrelid = 't_usuario'::regclass;

    EXECUTE format('ALTER TABLE t_usuario DROP CONSTRAINT %I', pk_nome);
END $$;

ALTER TABLE t_usuario DROP COLUMN id;
ALTER TABLE t_usuario RENAME COLUMN id_int TO id;
ALTER TABLE t_usuario ADD PRIMARY KEY (id);

-- O @GeneratedValue(strategy = IDENTITY) da entidade espera que o banco gere o próximo id.
ALTER TABLE t_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Sem isto a sequência começaria em 1 e colidiria com os usuários já migrados.
SELECT setval(
    pg_get_serial_sequence('t_usuario', 'id'),
    COALESCE((SELECT max(id) FROM t_usuario), 0) + 1,
    false);

-- ---------------------------------------------------------------------------
-- 5. Recria as chaves estrangeiras, agora apontando para a coluna integer.
-- ---------------------------------------------------------------------------
DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT * FROM referencias_para_usuario LOOP
        EXECUTE format(
            'ALTER TABLE %s ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES t_usuario(id)',
            r.tabela,
            'fk_' || replace(r.tabela, 't_', '') || '_' || r.coluna,
            r.coluna);
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 6. Conferência: nenhuma referência pode ter ficado órfã.
-- ---------------------------------------------------------------------------
DO $$
DECLARE r record; orfas integer;
BEGIN
    FOR r IN SELECT * FROM referencias_para_usuario LOOP
        EXECUTE format(
            'SELECT count(*) FROM %s t WHERE t.%I IS NOT NULL AND NOT EXISTS (SELECT 1 FROM t_usuario u WHERE u.id = t.%I)',
            r.tabela, r.coluna, r.coluna) INTO orfas;

        IF orfas > 0 THEN
            RAISE EXCEPTION 'restaram % referencia(s) orfa(s) em %.%', orfas, r.tabela, r.coluna;
        END IF;
    END LOOP;

    RAISE NOTICE 'migracao concluida sem referencias orfas';
END $$;

COMMIT;
